### PR TITLE
Asus Zenbook UX310UAK "silently"

### PR DESCRIPTION
**Pull request by fredo61**
NBFC-Config file "silently" for 'Asus Zenbook UX310UAK'
Stefan Hirschmann 's - [NoteBook FanControl](https://github.com/hirschmann/nbfc)
[ASUS Zenbook UX310UA-FC341T gold (90NB0CJ-M05320) @ heise online - Preisvergleich](https://www.heise.de/preisvergleich/asus-zenbook-ux310ua-fc341t-gold-90nb0cj-m05320-a1513984.html)
[ASUS ZenBook UX310UA @ Asus](https://www.asus.com/Notebooks/ASUS-ZenBook-UX310UA/)

Thx to: Stefan +xant1, jws

[NoteBookFanControl @ fredo](https://github.com/fredo61/hello-its-me/tree/master/NoteBookFanControl)
include Review/Testbericht @ Windows 10.0.14393-1607 - 64 Home

(My first file @ GitHub ...sorry, wenn ich da was falsch gemacht haben sollte)

### CODE REVIEW

**Comment by hirschmann** [comment]
Thanks for the config.
Does the Zenbook UX310UA**K** actually exist? I've searched for it and found the Zenbook UX310UA only.

**Comment by fredo61** [comment]
Hi Stefan
There are apparently two Board + Bios versions: UX310UA + UX310UAK.
My daughter's Zenbook identifies itself as UX310UAK in Bios and with the tool Aida64.
I think you will not be able to see it until you analyze it.

My and ConfigFile from 'plieningerweb' (Asus Zenbook UX310UA.xml) has the same base (Asus Zenbook Flip UX360UAK.xml).
I've used it as a base because of the same CPU.
You saw the german test report in my git? (URL see above)
There I have analyses and modified the FanSpeed-Values in 100/8=12,5%-steps as accepted from controller.
Created a new silent ThresholdTable and test it with Aida64-System-Stability-Test for ~1h.
Enabled,Auto - CPU: <70°C @ 25% (PCH: 59°C / SSD: 32°C) ...without DiskStress
Disabled,Manually - CPU: ~66°C + 50% Lüfter (PCH: 56°C / SSD: 41°C) ...with DiskStress

What are the two RegisterWriteConfiguration-Sections?
I've found that value in a dump, but I haven't understand and set the Description to '-KAx-' (No idea)
Is there a documentation for this?
For improvement of the reaction I had EcPollInterval reduced the last.
-- 
Gruß fredo

**Comment by hirschmann** [comment]
Jep, I've read your report and the thresholds seem to be fine.

> What are the two RegisterWriteConfiguration-Sections?

You tell me. After all it's your config. If you don't know what they do, try to delete them and see what happens.
The _RegisterWriteConfiguration_ is documented in the wiki: https://github.com/hirschmann/nbfc/wiki/Register-write-configuration

Often times they are used to overwrite the current EC's current temperature readings to prevent the EC's own logic from interfering with NBFC. This is quite a hacky solution, but its ok if it works without side effects ;)

Anyway, please describe the _RegisterWriteConfigurations_ properly, or don't describe them at all.
"-KAx-" is a pretty confusing description.

**Comment by hirschmann** [comment]
Sorry, I've overlooked the comment of your last commit.
Thank you very much for your effort 👍

**Pull request merged**
