### PR TITLE
Added HP Spectre x360 Convertible 13-ae0xx config file

### PR DESCRIPTION
**Pull request by mariusauer**

### CODE REVIEW

**Comment by hirschmann** [comment]
Thank you for your pull request!
The config looks fine, but I have some questions:
1. Are there really only 3 different fan states (0, 1, 2)?
2. It seems like the config will only turn the fan on or off. Is it supposed to be like that?

**Comment by mariusauer** [comment]
This config only writes to the register that turns the fan on or off.
Value 2 = force fan off
Value 0 = auto controlled fan

I have not been able to find a way to control the RPM of the fan. I don't really have any experience with DSDT and the EC register. I have tried running the ec-probe utility while the fan speeds are changing, but I cannot seem to find the register for adjusting the fan speed.

Here is the code section in the DSDT for turning the fan ON/OFF:
```
If(LNot(LEqual(Arg0, Zero)))
{
    Store(Zero, \_SB_.PCI0.LPCB.EC0_.SFAN)
}
Else
{
    Store(0x2, \_SB_.PCI0.LPCB.EC0_.SFAN)
}
```

**Comment by hirschmann** [comment]
Thanks for the clarification!
I think at least being able to turn the fan off until the temperature hits a certain threshold is better than nothing, so I'm gonna merge this PR.

**Comment by sisti00** [comment]
it works with my Hp pavilion 15 n 253sl, but only for on off. I modified it with min speed value 8 and max speed value 88, which i belive it is max speed register (found with rw-everything). this configuration for me WORKS VERY WELL! i'm able to control the fanspeed as i want

**Comment by MarioAlbe90** [comment]
hi, looking at this i started playing in the settings in my  Spectre x360 Convertible 13-ap0xx,
I set speed from 0 to 100, I could observe that it works in the same way as your config for 0 and 2, moreover it started and stopped immediately at 10 and at 40 it started at minimum speed, I rise seeing an increase at 41, 46 and 51, than at 100 it crashed.
I have overheating problem, looking to manage it since 2019, I need to use this very expensive laptop always in the comfort config in the HP command center, I would like to use still other profiles like performance speeding at max the fans since the computer is getting old and is not performing that good.
hope I could help someone with the same issue, sorry but I didn't understand anything about instructions so I have no idea on what effectively to change.
may it works also for 13-ae0xx models

**Pull request merged**
