### PR TITLE
Changed config for the K501UX

### PR DESCRIPTION
**Pull request by ragekit**
Check first commit down there for explanation

### CODE REVIEW

**Comment by hirschmann** [comment]
Thanks for the config!

I have some questions before I merge this pull request:
1. If the right fan only has 2 possible states (on/off), why don't you set MaxSpeedValue to 1, so that min = 0, max = 1?
2. Does the config still work if you increase the poll interval? This would result in less CPU load.
3. Could you please add a description to the RegisterWriteRequests?
4. Why is FanSpeedResetValue equal to MaxSpeedValue? This means the fan will be reset when set to 100% speed. Is this the intended behavior?

**Comment by ragekit** [comment]
Inestigating all those. 

for 1) totally, it can/should be 1 I think
2) Im going to make some test for that
3) I copied it from another config that apparently works for the UX, Im not sure how to describe them. All I know it that I need to write to them. If not, the EC seems to auto reset (if that makes sense ??)
4) this is an error, it shouldnt reset. Even reset on exit should be unchecked since it seems the uc reset anyhow.

Does that makes sense to you ?

Im going to do further test

**Comment by ragekit** [comment]
Ok i checked : for 3) Any value written to those register seem to work. If I dont write anything, then it doesnt work. Still a mystery as to why.

Still testing what max value I can set to polling

**Comment by hirschmann** [comment]
Great!
When you've finished testing, just update the pull request.

**Comment by ragekit** [comment]
im around 200ms and still works. What would be the max you think ? 500ms ? 

Still don't know how to describe those register btw, not a problem ?

**Comment by hirschmann** [comment]
I suggest to start at 3000ms and then decrease by 250 - 500ms until it works without problems.
A description would just be nice to have. I will accept the pull request without a description, as long as the config works properly.

**Comment by keresztesizoli** [comment]
Hi,

how can I use this config?
I have this ASUS model, I'd like to use it.

Shall I wait until it will be published or can I use it somehow?
I don't know what to do with these xml files.

Thx
Zoli

**Comment by keresztesizoli** [comment]
Hi,

I'm using this config.
Question is what is the threshold temperature? 
If I switch to "enable" at Fan control service status, the fans don't turn on. 
I'd like to know wheter or not this is normal.

Thx in advance!

**Comment by ragekit** [comment]
I didn't forget this. I'm just swamped by work now. Ill try to find a way to properly finish this config

**Comment by keresztesizoli** [comment]
Hi ragekit,

any progress on it? When can we get your final work?
I'm waiting for it! :-)

Zoli

**Comment by ragekit** [comment]
Ok, new update. Ive been able to put the polling up to 300ms but more it does not work

**Comment by ragekit** [comment]
urgh no in fact 200ms is safer

**Comment by keresztesizoli** [comment]
I don't know why, but on "enabled" mode tha fan won't turn on. Even on very high temperatures! 
Is it normal at this point of your config or not?

Thx,
Zoli

**Comment by ragekit** [comment]
The fan should turn on starting at 65deg. Its taken from a computer with similar spec. 
Im changing the pol again it seems 200ms is juuuuuuuuust almoooost not enought

**Comment by DJWassink** [comment]
just tested this config on my laptop, works pretty good.

Fun fact: Downloaded Prime95 today and my CPU wasn't able to get higher then ~70degrees with the fan spinning on 25%

**Comment by hirschmann** [comment]
Thanks @ragekit for your effort and thanks @DJWassink for testing!

**Pull request merged**
