### PR TITLE
Add config for Acer Aspire E5-575G

### PR DESCRIPTION
**Pull request by cymug**

### CODE REVIEW

**Comment by alezost** [comment]
You say this config is for `E5-575G`, but the Notebook-Model in the xml file is `E5-471G`.

**Comment by cymug** [comment]
Changed it to `E5-575G`

**Comment by alezost** [comment]
My notebook model is "E5-576-33BR".  I have tried this config, and it works brilliantly.  Thank you!

**Comment by hirschmann** [comment]
@cymug
Thank you very much for your config.
Sorry it took me so long to respond. I was quite busy in the last couple of months :/

@alezost
Thank you for your feedback. Good to know that this also works for the E5-576-33BR

**Pull request merged**
