### PR TITLE
Initial checkin HP Pavilion 17-ab240nd configuration file.

### PR DESCRIPTION
**Pull request by Erriez**
Can you add my HP Pavilion 17-ab240nd configuration file?

Note: I've added specific 17-ab240nd documentation in the README.md file in a separate feature branch which is not part of this pull request branch, because I could not find a good location to save it:
~~https://github.com/Erriez/nbfc/tree/hp-17-ab240nd~~

Thanks.

### CODE REVIEW

**Comment by hirschmann** [comment]
Thank you very much for your config 👍 
I also like your documentation. Imho you should put it into a separate repository which contains only the config file and the documentation. I think this would look cleaner than a feature nbfc/feature branch.

**Comment by Erriez** [comment]
Thanks for your fast response. Tomorrow I'll delete my fork and create a new repository with the readme as you suggested. I can point to your project which now contains the config file.

**Comment by Erriez** [comment]
README.md is now available in my fork master branch:
https://github.com/Erriez/nbfc-hp-pavilion-17-ab240nd

**Comment by sisti00** [comment]
thank you, it works with hp pavilion 15 n253sl, but only for few minutes. I set the critical temperature to 95° but the laptop never reach 70° so that is not the problem. Do you have any suggestion?

**Pull request merged**
