### PR TITLE
Create Xiaomi Mi Book (TM1613, TM1703)

### PR DESCRIPTION
**Pull request by sshilko**
Xiaomi Mi Book 13 TM1703 (2018 8gen i7 8550U) and previous generations of Xiaomi Mi Book.
More details on xiaomi website:
http://en.miui.com/thread-1759175-1-1.html

Differente genrations have similar controller, might work with other Xiaomi Mi Book models too

### CODE REVIEW

**Comment by hirschmann** [comment]
Looks good, thank you very much 👍

**Comment by victorcerezuela** [comment]
sorry but i'm new in this and i dont know how to download the config, i've just recived my laptop and fans are a little bit noisy

**Comment by hoaivan** [comment]
Doesn't work for TM1701. If use, this will cause laptop failed to load bluetooth.

**Comment by sshilko** [comment]
Never used bluetooth and cant see how is that connected to fan speeds

**Comment by hoaivan** [comment]
it writes to the wrong address in register which make bluetooth die. If i shutdown notebook fancontrol, restart laptop, bluetooth will work again

**Comment by mitokohaku** [comment]
Want to surpport TM1701,the computer is always hot,I want to make it cool down.

**Comment by HorrZzz** [comment]
Want to surpport TM1701，please！

**Pull request merged**
