### PR TITLE
Support for the Sony Flip 15A SVF15N2C5E

### PR DESCRIPTION
**Pull request by colingg**

### CODE REVIEW

**Comment by diman94** [comment]
Hello. I've tried it on my Sony Vaio Flip 15A SVF15N2M2R and I have some kind of issue. It works really perfect when I use my Vaio in Laptop mode but when I switch to Tablet mode (flip screen and close) my laptop fan **speeds up to 87%** although the temperature is still about 39-43 degrees. The only solution is to switch to Read-only mode. Do you have any ideas how to fix it? The simpliest solution I see is to add option to automatically disable it in the tablet mode.

**Comment by hirschmann** [comment]
@colingg
Thank you very much for the config!
Before I merge this pull request, I have 2 questions:
1. Why are there only 2 TemperatureThresholds and thus onyl 2 possible fan speeds?
2. Do you have the same problems that @diman94 described?

@diman94
It's actually possible to automate NBFC.
You can enable read-only mode: `nbfc start --readonly`
Or you can switch back to enabled: `nbfc start --enabled`
See https://github.com/hirschmann/nbfc/wiki/Command-line-interface

I'm also pretty sure Windows posts an event into the Windows Event Log when it switches into tablet mode.
Maybe you could create a scheduled task which is triggered by an event and changes the NBFC service's status according to your needs.

**Comment by diman94** [comment]
@hirschmann I thought about a small script, but your solution looks even better. I'll try to figure it out tomorrow.

**Comment by colingg** [comment]
@hirschmann No idea, I remember finding the initial config somewhere on a sony forum, but was unable to find the original thread again. I just thought it would be a good idea to add this to the repo.

**Comment by diman94** [comment]
@colingg @hirschmann this Sony forum topic https://community.sony.com/t5/VAIO-Hardware-Networking/The-Sony-Vaio-Flip-and-its-noisy-fan/td-p/234627/page/67 and the original one https://www.computerbase.de/forum/showthread.php?t=1070494&page=41&p=15825308&highlight=sony#post15825308

**Comment by diman94** [comment]
@colingg @hirschmann in fact it works the way it's said in the original thread:
"TEMP 0-60c: fan speed = 0, TEMP over 60: fan speed BIOS-controlled. "
I observe exactly the same situation. But it is a lot better than having fan blowing when you just reach ~45°. It is what Sony coudn't do for a year of user complaints.

**Comment by diman94** [comment]
I've read something with google translate. There are acrually two profiles. The first just break BIOS fan control so it doesn work below 60° and the second works as a normal profile would work, but it doesn't disable bios fan control so the polling interval is 1750ms (bios writes every 3000ms).
Now I'm trying the second one SVF14N1C5E (2) in tablet mode and my fan doesn't go insane! It seems to work, the only thing is that it is said that short polling interval might cause some troubles with battery indicator showing zero charge randomly.
zip file http://www.computerbase.de/forum/attachment.php?attachmentid=431494&amp;d=1406961141

**Comment by hirschmann** [comment]
I have thought a lot about this config and I finally came to the conclusion that it causes too many problems, so I will not merge this pull request.
Nevertheless, thank you very much for your effort.

**Pull request closed without merging**
