### PR TITLE
New config for Lenovo ThinkPad L390 i7-8565U

### PR DESCRIPTION
**Pull request by bekliev**
Accordingly to [this guideline](https://github.com/hirschmann/nbfc/blob/master/CONTRIBUTING.md#configs) for config files, I'm answering by their order:
1. This config is based on **Lenovo U41-70.xml** config file, cause of write and reads I think. Any other of ThinkPad line configs didn't work for my laptop.
2. Repeating: based on **Lenovo U41-70.xml** config.
3. This config doesn't require any modifications - just dropdown -> find it in the list -> Press **Apply** => and it will work.

Changes to base config:
1. Changed threshold of starting temperatures to be matched with system settings untill 68 degrees works as system fan set up. But from 68+ degrees fan set up to 85%, and after 90+ degrees set to 100%. Remark: system settings wasn't turn on the fan for even 85%, the max power was 72%.
2. Set fan's **Min speed** to 255 and **Max speed** to 64 - to be 100% matched with **Current fan speed** indicator. I mean **Target fan speed** and **Current fan speed** is identical with these settings.
3. Added CPU model to the config name, cause I thought it can cause different coolers - I don't know for sure.

### CODE REVIEW

**Comment by hirschmann** [comment]
Thank you very much for your effort.
I'd love to merge your pull request, but currently it doesn't pass all the unit tests:

> Lenovo ThinkPad L390 i7-8565U config is not valid:
> - All up-threshold values must be lower than the critical temperature
> --> At least one up-threshold is higher than or equal to the critical temperature: 100
> 
> 
> Expected: True
> Actual:   False

see: https://ci.appveyor.com/project/hirschmann/nbfc/builds/24547666/tests

Please fix this small issue and update the pull request, so I can merge it :)

**Comment by bekliev** [comment]
Done 😃

**Comment by bekliev** [comment]
Fixed the issue - can merge the PR

**Comment by hirschmann** [comment]
Thanks for the fix :)

**Pull request merged**
