### PR TITLE
Create HP Notebook 15-ba010ng.xml

### PR DESCRIPTION
**Pull request by webloft**
Made this config for an older model just to see how it works =)

### CODE REVIEW

**Comment by hirschmann** [comment]
Thank you very much for your config.
Looks good!


For visibility - this comment is inside the config file:
> It seems not possible to completely turn off the fan but on lower values it is not even noticeable anymore.
> There is a weird offset between read and write values. To correctly display the percentage a bezier-curve would be needed. These values may be need to adjust on the target device also.
> The write register should not be greater than 0x3F, otherwise the fan spins on and off with further values. I was not able to find a pattern/bitmask here. It works well from 0x03 - 0x34.

**Comment by RiotThanos** [comment]
thank you very much you are the best

**Comment by mtamer93** [comment]
Could you make a config file that can control two fans?

**Comment by webloft** [comment]
@mtamer93 I think it is not possible to create a config file without access to the physical device (also without knowing the fans actually spin up)

**Comment by mtamer93** [comment]
> @mtamer93 I think it is not possible to create a config file without access to the physical device (also without knowing the fans actually spin up)

I have HP Gaming Pavilion - 15-cx0039nt Can you make a config for this laptop in order to work two fans? Your config file works for one fan.

**Comment by webloft** [comment]
@mtamer93 This config may work with the CPU cooler of HP 15xxxx. However I guess your second cooler is not attachted to the ACPI DSDT but to the GPU BIOS instead. Depending on the GPU chip it should be possible to control the fan but not with this tool (and no I don't know which tool could work for your GPU).

**Comment by mtamer93** [comment]
@webloft Thank you for your explanation.

**Comment by ananjaser1211** [comment]
Thanks for the config. works great for the CPU cooler of my CX0056WM. 

looking into ways to make the GPU cooler work, if i figure it out ill post it here

**Comment by ghost** [comment]
That will be great

3 Eyl 2020 Per 21:03 tarihinde AnanJaser <notifications@github.com> şunu
yazdı:

**Comment by xCuri0** [comment]
@webloft do you have any more information about using bezier curve ?

**Comment by webloft** [comment]
@xCuri0 It means that the values cannot be mapped on a linear scale with the percentage of the nbfc app as the values might be only some weird hard coded presets that just jump to an another RPM value in real.

**Pull request merged**
