### PR TITLE
Create Acer Aspire V3-471G.xml

### PR DESCRIPTION
**Pull request by miwtoo**
dump file

00: 00 00 08 01 00 00 00 00 00 00 29 9D AC AD 29 29 
10: 29 29 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
30: 00 00 00 00 00 00 00 00 00 00 00 00 02 14 F1 00 
40: A3 13 C8 03 00 00 00 00 00 00 00 00 00 03 33 00 
50: 06 02 00 00 00 04 00 00 4B 34 34 00 00 01 00 00 
60: 43 82 50 50 C1 06 00 00 00 0C 00 00 16 01 00 02 
70: 0A 2B 80 00 00 E0 40 63 D2 00 E5 0B B2 40 00 00 
80: 00 0C 22 30 00 00 00 00 33 0C 0C 0E 0E 11 11 2B 
90: 2B 00 00 00 04 00 32 00 00 00 00 00 00 00 00 00 
A0: 00 00 00 00 00 00 00 00 00 FF 00 00 00 00 00 00 
B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
D0: 00 00 1E 00 00 00 00 FF 00 00 00 00 00 00 80 80 
E0: 00 00 D4 30 00 00 00 00 00 00 00 00 00 00 00 00 
F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

### CODE REVIEW

**Comment by hirschmann** [comment]
Thanks for your config.
Seems like it is based on the _Aspire V5-572G_ config. Have you also tried the _Aspire V3-371G_ config?

Why is the poll interval so low? Do you experience any problems if you increase it e.g. to 1000?

**Comment by miwtoo** [comment]
Yes. this based on  Aspire V5-572G it work on V3-471G same but not work well it still Slow rotation alternately i don't know how to fine poll interval.

i try set 1000 it still work same 100

**Comment by hirschmann** [comment]
Thanks for your response and for your effort.
Unfortunately, I can't accept this pull request, because, as you said yourself, the config does not work well. Sorry.

**Comment by miwtoo** [comment]
I understand, I tried to solve it, but I did not work well.

**Pull request closed without merging**
