### PR TITLE
Add config for HP Pavilion Gaming 15-ec0xxx(Ryzen 3550H)

### PR DESCRIPTION
**Pull request by tejaswivykuntam**
Previous pull request failed because of missing "Fanspeed 100" field.

### CODE REVIEW

**Comment by tejaswivykuntam** [comment]
Critical temp was lower than one of the thresholds.

**Comment by Quarterblad** [comment]
How did you find this register (45)?

**Comment by tejaswivykuntam** [comment]
Look at the SUPERIO chip's datasheet. Usually takes trial and error to determine the register.

**Comment by Quarterblad** [comment]
What chip is on your board? SCH5027D?

**Comment by tejaswivykuntam** [comment]
Yes.
image

**Pull request closed without merging**
