### PR TITLE
add config for Asus Zenbook UX430UA

### PR DESCRIPTION
**Pull request by sladiri**
I created this config based on the Asus Zenbook UX430UQ config by erkexzcx. (I the UX430UA config in master and imported the UX430UQ one).

I wanted to create a silent semi-passive config, and I tested it with Intel's Extreme Tuning Utility and its 5 minute CPU stress test.

According to NBFC's speed reading it actually maps the stock fan curve pretty well, just that my config lowers the fan speed by 12.5% across the entire temperature range. In the stress test (while charging too) the default settles at about 77degC package temp and 50% fan speed. My config got up to 80degC and 35.7% speed. This config allows the laptop to be silent at 0% speed most of the time.

sensors from XTU while CPU stress test and charging
stock: https://ibb.co/c825tG
semi-passive: https://ibb.co/gELKLw

### CODE REVIEW

**Comment by sladiri** [comment]
I increased the lower thresholds slightlty so it is less likely that the fan spins up for a short time during youtube and music playback.

**Comment by hirschmann** [comment]
Thanks for the config. Looks good so far. 

The only problem is, that there is no threshold which puts the fan at 100% speed.
Although the NBFC's critical mode would kick in if the temperature is too high, configs shouldn't rely on it.

**Comment by sladiri** [comment]
I understand, yes I did rely on the critical temperature setting. I added fan speed settings up to 100% now.

**Comment by hirschmann** [comment]
Thank you for the changes 👍

**Comment by NocneNiebo** [comment]
<TemperatureThresholds>
        <TemperatureThreshold>
          **<UpThreshold>0</UpThreshold>**             < this is not bad? <UpThreshold>52</UpThreshold>
          <DownThreshold>0</DownThreshold>                                       maybe better this ^
          <FanSpeed>0</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>62</UpThreshold>
          <DownThreshold>52</DownThreshold>
          <FanSpeed>12.5</FanSpeed>

**Comment by NocneNiebo** [comment]
<UpThreshold>0</UpThreshold>          < this is not bad? <UpThreshold>52</UpThreshold>
          <DownThreshold>0</DownThreshold>                                       maybe better this ^
          <FanSpeed>0</FanSpeed>

**Pull request merged**
