### PR TITLE
Add Lenovo Ideadpad U430p

### PR DESCRIPTION
**Pull request by mattconsto**
Basically a copy of Lenovo Ideadpad U330p. I have been using the U330p config and it works great, but as it is for the previous model of this laptop it has the previous models name.

### CODE REVIEW

**Comment by hirschmann** [comment]
Looks good.
Thank you very much!

**Comment by mattconsto** [comment]
@AdibSadman Either try one of the Acer Aspire V configs and hope it works (no promises that it will work and no promises that it won't cause damage) or follow this guide: https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config

**Comment by AdibSadman** [comment]
I tried all the configs recommended by nbfc command-line but none worked. Also I have seen the guide but it's a little tedious for me. ((Sorry)). Could you add please add it? Thanks @mattconsto

**Comment by AdibSadman** [comment]
So yeah please add Acer Aspire VX5-591G it will be extremely helpful.

Keep up the awesomeness!
Cheers.

শনি, 23 জুন, 2018 10:36 তারিখে Matthew Consterdine <notifications@github.com>
লিখেছেন:

**Pull request merged**
