### PR TITLE
Create Lenovo Ideapad U330p.xml

### PR DESCRIPTION
**Pull request by sewagolubkow**
Lenovo U330p - Fan Problem Fixed

### CODE REVIEW

**Comment by sewagolubkow** [comment]
Register 144:
00 = Auto
01 = Full speed
02 = Keep current speed

Register 146:
FF to 01 = Fine-tuning fan speed

Register 147:
FF = Fan off / Minimal Speed (step 0)
02 = Minimal to mid Speed (step 1)
01 = Mid to max speed (step 2 - final step)

**Comment by hirschmann** [comment]
Thanks for your effort! :)

Unfortunately there are some problems which need to be fixed before I can merge your pull request:
You have set _ReadWriteWords_ to _true_ which means NBFC will treat 2 8bit registers as one 16bit register. Therefore the fan configuration "146" will affect both, register 146 and 147.

The problem is, that you have defined fan configurations for register 146 and 147, so reads/writes will overlap. Additionally the fan config for register 144 will (unintentionally) affect reg 145.

I suggest to replace the 3 existing fan configurations with one that looks like this:
```xml
<FanConfiguration>
  <ReadRegister>146</ReadRegister>
  <WriteRegister>146</WriteRegister>
  <MinSpeedValue>768</MinSpeedValue>
  <MaxSpeedValue>257</MaxSpeedValue>
  <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
  <MinSpeedValueRead>0</MinSpeedValueRead>
  <MaxSpeedValueRead>0</MaxSpeedValueRead>
  <ResetRequired>true</ResetRequired>
  <FanSpeedResetValue>0</FanSpeedResetValue>
  <FanDisplayName />
  <TemperatureThresholds />
  <FanSpeedPercentageOverrides>
    <FanSpeedPercentageOverride>
      <FanSpeedPercentage>0</FanSpeedPercentage>
      <FanSpeedValue>65535</FanSpeedValue>
      <TargetOperation>ReadWrite</TargetOperation>
    </FanSpeedPercentageOverride>
  </FanSpeedPercentageOverrides>
</FanConfiguration>
```
Read/WriteRegister: 146 --> because ReadWriteWords = true, this will treat 146 and 147 as one 16bit register, where 146 = LSB and 147 = MSB

MinSpeedValue: 768 --> 0x02FF + 1; this is the min speed according to your description plus one extra step for "fan off" (which will be overridden by FanSpeedPercentageOverride)

MaxSpeedValue: 257 --> 0x0101; this is the max speed according to your description

FanSpeedResetValue: 0 --> Just a guess. Maybe it is ok to set 'ResetRequired' to false and ignore this. Anyway you have to make sure, that the EC-BIOS actually controls the fan after NBFC has been stopped

FanPercentageOverride: Value: 65535 = 0xFFFF; Percentage: 0; If you set the fan speed to 0%, usually NBFC writes MinSpeedValue to the write register. Because of this FanPercentageOverride, NBFC will write 65535 instead, whenever the fan speed is set to 0%
***
Some more questions:
- Why do you set register 144 to 0 and never reset it?
- Does "02 = Keep current speed" mean the EC will reject writes to register 146/147 if register 144 is 2?
- What is the default value of register 144?

***
I hope you can sort out those problems, because I'd love to accept your pull request.
Let me know if you need further assistance :)

**Comment by sewagolubkow** [comment]
Hey, thanks so much for this detailed reply.
I don't know if we can set up the config with 16bit. I didn't know about the ReadWriteWords setting. Register 147 should jump between 8bit values "FF", "02" & "01", as these set a rough band for fine-tuning the speed, which happens on register 146.
I'll definitely try your suggestions, I'll post the correct setting within the next few weeks, when I get my notebook back.
- Register 144 ist just here to "clean" the fan: With a lenovo software, the user can push the fan to the limit, in hope of removing the dust.
- Yes, value "02" on register 144 will override everything and keep the current fan speed
- Default value of 144 is 0 of course

Thanks again for this awesome piece of software!

**Comment by sewagolubkow** [comment]
Also, I didn't know about LSB & MSB, as I've never studied computer science in much detail, but thats cool yo... very interesting

**Comment by sewagolubkow** [comment]
I've updated the config - [see commit](https://github.com/sewagolubkow/nbfc/commit/2ca5e54dad8b71dd6814079fe660b19af7ac13b3).
It seems that register 144 is marking the fan for auto control. Is the value 0x80, the bios handles the Speed of the fan. On 0x00 nothing is moving.
Thanks again for the help and the software!

**Comment by hirschmann** [comment]
Thank you very much for the config!
Great work :+1:

**Pull request merged**
