### PR TITLE
Config for Asus Zenbook Pro UX550(VE)

### PR DESCRIPTION
**Pull request by FloThinksPi**
Should work on all UX550 tough, but is only testet on UX550VE

### CODE REVIEW

**Comment by hirschmann** [comment]
Looks good, thank you very much!

**Comment by FloThinksPi** [comment]
@gobi84 The Fan is always at 12.5% so always on. Anyway it is also always Safe because The system is downclocking above 80°c automatically. Under high load and with CPU + GPU The device unfortunaly always downclocks because of high Temperaturen even when The Fans are Full on. Not The best thermal Design .

So i tweaked The Profile to be Most silent when browsing or watching Videos, thus The fairly high step Up Limit. But under real load The Fans kick in quite early compared to Default so cooling is after all better and You get better short term Performance because downclocks Happen later ;)

**Comment by gobi84** [comment]
Thanks for your comment. Yeah, I've noticed minimum 12,5% for the idle mode. I wonder is it safe to make a little edit in your config to make it completely silent until CPU reach 48°c just for browsing or watching videos. What are your thoughts on this? I'll leave the rest of your config without changes

**Comment by gobi84** [comment]
Ok, i'll try to off the fans in idle and will observe the temperature how it's handling with simple tasks. Thanks for your comments nad config file. Great Job!!!

**Comment by 40sam40** [comment]
Hi, how can I get the config for Zenbook UX434?

**Pull request merged**
