### PR TITLE
Added authors and fixed a threshold issue

### PR DESCRIPTION
**Pull request by ranyyy**
I fixed a issue w/ the threshold and added the authors (Rany H. and Stefan Hirschmann) :)
Oops I meant a threshold issue. Sorry!

### CODE REVIEW

**Comment by ranyyy** [comment]
Sorry I gave you an older copy of the file.

**Comment by ranyyy** [comment]
Sorry I gave you an older copy of the file.

**Comment by ranyyy** [comment]
I'll update the file when I can immediately most likely after a few hours.

**Comment by ranyyy** [comment]
Fixed the file :)

**Comment by hirschmann** [comment]
I didn't create this config, please remove me from the authors list.
Unfortunately I don't remember who actually created it, so let's simply name him/her 'unknown' :)

If there are multiple config authors I recommend separating them by comma, like this:
`<Author>unknown, Rany H.</Author>`
because it is easy to read and easy to parse.

**Comment by ranyyy** [comment]
OK, I updated the authors list :)

**Comment by hirschmann** [comment]
Thanks :+1:

**Pull request merged**
