### PR TITLE
Add Acer Aspire V3-571G config

### PR DESCRIPTION
**Pull request by lzsaver**
Author: Solteks from acerfans.ru
Version: 2016/05/28

### CODE REVIEW

**Comment by hirschmann** [comment]
Thank you for your config.

Could you please explain what you mean by _TermoProfile_ ([line 69](https://github.com/hirschmann/nbfc/pull/248/files#diff-085328a693f023f46117578d61503ec8R69)) and how it works?

**Comment by lzsaver** [comment]
> Could you please explain what you mean by TermoProfile (line 69) and how it works?

It switches to the low-TDP thermotable witch gives 100% of the fan power on the last stage, then informs the notebook that it is artificially overheated.

Also this profile is designed to work with disabled BD_PROCHOT using TrottleStop (what about to add this feature to NBFC?), otherwise users will get CPU throttling as soon as they reach 80°C.

**Comment by hirschmann** [comment]
Thanks for your explanation.
Unfortunately I think I can't accept the config in the current state, because I want all "official" configs to be easy to use, even for inexperienced users.
A dependency on ThrottleStop would contradict this objective.

I've tried to simplify your config:
- "thermo profile" and "fan on/off" should probably only have 2 different states, so I basically converted them to on/off switches
- I've also removed all the unnecessary temp. thresholds for "thermo profile"
- you said the CPU throttles at about 80°C, so I've set the critical temperature to 75°C

It would be awesome if you could test the simplified config and tell me if it works properly.
Additionally, some more things to consider:
- maybe the "thermo profile" switch is not even required if you run the config with BD_PROCHOT  enabled
- when I look at the "fan controller"'s min/max values, it looks like it doesn't actually control the fan, but manipulates temperature readings. If this is the case, maybe "max value" should be set to something below 80°C instead of 85°C, otherwise the CPU would throttle. (this is just a guess, maybe I'm wrong)

The simplified config: [Aspire V3-571G.zip](https://github.com/hirschmann/nbfc/files/1069020/Aspire.V3-571G.zip)

Regarding BD_PROCHOT  support in NBFC:
I can't write platform independent code to enable/disable BD_PROCHOT, so I'd have to at least write platform specific code twice (windows & linux). I'm not sure if enough configs would use this feature to make it worth the effort.

**Comment by lzsaver** [comment]
I'll check it. Thanks.

**Comment by lzsaver** [comment]
I tested your simplified config for several months and found no problems. Thank you, hirschmann.

**Comment by hirschmann** [comment]
Thanks for testing 👍

**Pull request merged**
