### PR TITLE
Create Asus Zenbook UX410UQ.xml

### PR DESCRIPTION
**Pull request by Jonas1312**
Same as all asus zenbook config files

### CODE REVIEW

**Comment by lkmoe** [comment]
Hi, is there any recommended changes to apply to this config file / configuration for model UX410UQK ?
Thanks in advance (:

**Comment by Jonas1312** [comment]
Hi @lkmoe , this config file contains my thresholds but you can change them if you prefer.
[https://github.com/hirschmann/nbfc/wiki/Temperature-threshold](https://github.com/hirschmann/nbfc/wiki/Temperature-threshold)

**Comment by hirschmann** [comment]
@Jonas1312
Thank you very much for the config!
Looks good to me. However, it looks like you are still trying to figure out the best temp. thresholds (your latest commit was 3 hours ago).

I will merge this PR as soon as you tell me you've finished the config.

**Comment by Jonas1312** [comment]
Hi,
The current config is perfect, I won't change it again :)

Thanks for your amazing software!

**Comment by hirschmann** [comment]
Great!
I'm glad you like NBFC. I currently don't have a date for the next release.

**Comment by lkmoe** [comment]
@Jonas1312  I'll try out your config and thresholds then - thanks a lot! :)

@hirschmann And I can only agree with @Jonas1312: Thank you very much for your amazing software! :))

**Comment by tomas1lamr** [comment]
Works for me also on UX430UA. Thanks!

**Pull request merged**
