### PR TITLE
Add Asus Vivobook TP301UA

### PR DESCRIPTION
**Pull request by NavidDanesh**
Please add this config for Asus Vivobook TP301UA

### CODE REVIEW

**Comment by NavidDanesh** [comment]
<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<NotebookModel>ASUS VivoBook TP301UA</NotebookModel>
<EcPollInterval>150</EcPollInterval>
<ReadWriteWords>false</ReadWriteWords>
<CriticalTemperature>90</CriticalTemperature>
<FanConfigurations>
<FanConfiguration>
<ReadRegister>151</ReadRegister>
<WriteRegister>151</WriteRegister>
<MinSpeedValue>0</MinSpeedValue>
<MaxSpeedValue>8</MaxSpeedValue>
<IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
<MinSpeedValueRead>0</MinSpeedValueRead>
<MaxSpeedValueRead>0</MaxSpeedValueRead>
<ResetRequired>true</ResetRequired>
<FanSpeedResetValue>9</FanSpeedResetValue>
<TemperatureThresholds>
<TemperatureThreshold>
<UpThreshold>40</UpThreshold>
<DownThreshold>0</DownThreshold>
<FanSpeed>0</FanSpeed>
</TemperatureThreshold>
<TemperatureThreshold>
<UpThreshold>47</UpThreshold>
<DownThreshold>41</DownThreshold>
<FanSpeed>12.5</FanSpeed>
</TemperatureThreshold>
<TemperatureThreshold>
<UpThreshold>55</UpThreshold>
<DownThreshold>48</DownThreshold>
<FanSpeed>25</FanSpeed>
</TemperatureThreshold>
<TemperatureThreshold>
<UpThreshold>65</UpThreshold>
<DownThreshold>56</DownThreshold>
<FanSpeed>50</FanSpeed>
</TemperatureThreshold>
<TemperatureThreshold>
<UpThreshold>75</UpThreshold>
<DownThreshold>66</DownThreshold>
<FanSpeed>75</FanSpeed>
</TemperatureThreshold>
<TemperatureThreshold>
<UpThreshold>85</UpThreshold>
<DownThreshold>76</DownThreshold>
<FanSpeed>100</FanSpeed>
</TemperatureThreshold>
</TemperatureThresholds>
<FanSpeedPercentageOverrides/>
</FanConfiguration>
</FanConfigurations>
<RegisterWriteConfigurations>
<RegisterWriteConfiguration>
<WriteMode>Set</WriteMode>
<WriteOccasion>OnWriteFanSpeed</WriteOccasion>
<Register>160</Register>
<Value>10</Value>
<ResetRequired>true</ResetRequired>
<ResetValue>10</ResetValue>
<ResetWriteMode>Set</ResetWriteMode>
</RegisterWriteConfiguration>
<RegisterWriteConfiguration>
<WriteMode>Set</WriteMode>
<WriteOccasion>OnWriteFanSpeed</WriteOccasion>
<Register>166</Register>
<Value>10</Value>
<ResetRequired>true</ResetRequired>
<ResetValue>10</ResetValue>
<ResetWriteMode>Set</ResetWriteMode>
</RegisterWriteConfiguration>
</RegisterWriteConfigurations>
</FanControlConfigV2>

**Comment by hirschmann** [comment]
Thanks for the config 👍 

The config itself looks good, but the filename has some flaws:
1. The config should have a .xml file extension
2. Avoid screeming caps in the filename

Please change the filename to `Asus VivoBook TP301UA.xml`

**Comment by NavidDanesh** [comment]
Sorry
I can't attach the xml in my post!
Now what should i do?

**Comment by NavidDanesh** [comment]
<?xml version="1.0"?>
<FanControlConfigV2 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NotebookModel>Asus Vivobook TP301UA</NotebookModel>
  <EcPollInterval>150</EcPollInterval>
  <ReadWriteWords>false</ReadWriteWords>
  <CriticalTemperature>90</CriticalTemperature>
  <FanConfigurations>
    <FanConfiguration>
      <ReadRegister>151</ReadRegister>
      <WriteRegister>151</WriteRegister>
      <MinSpeedValue>0</MinSpeedValue>
      <MaxSpeedValue>8</MaxSpeedValue>
      <IndependentReadMinMaxValues>false</IndependentReadMinMaxValues>
      <MinSpeedValueRead>0</MinSpeedValueRead>
      <MaxSpeedValueRead>0</MaxSpeedValueRead>
      <ResetRequired>true</ResetRequired>
      <FanSpeedResetValue>9</FanSpeedResetValue>
      <TemperatureThresholds>
        <TemperatureThreshold>
          <UpThreshold>40</UpThreshold>
          <DownThreshold>0</DownThreshold>
          <FanSpeed>0</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>47</UpThreshold>
          <DownThreshold>41</DownThreshold>
          <FanSpeed>12.5</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>55</UpThreshold>
          <DownThreshold>48</DownThreshold>
          <FanSpeed>25</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>65</UpThreshold>
          <DownThreshold>56</DownThreshold>
          <FanSpeed>50</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>75</UpThreshold>
          <DownThreshold>66</DownThreshold>
          <FanSpeed>75</FanSpeed>
        </TemperatureThreshold>
        <TemperatureThreshold>
          <UpThreshold>85</UpThreshold>
          <DownThreshold>76</DownThreshold>
          <FanSpeed>100</FanSpeed>
        </TemperatureThreshold>
      </TemperatureThresholds>
      <FanSpeedPercentageOverrides />
    </FanConfiguration>
  </FanConfigurations>
  <RegisterWriteConfigurations>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>160</Register>
      <Value>10</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>10</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
    <RegisterWriteConfiguration>
      <WriteMode>Set</WriteMode>
      <WriteOccasion>OnWriteFanSpeed</WriteOccasion>
      <Register>166</Register>
      <Value>10</Value>
      <ResetRequired>true</ResetRequired>
      <ResetValue>10</ResetValue>
      <ResetWriteMode>Set</ResetWriteMode>
    </RegisterWriteConfiguration>
  </RegisterWriteConfigurations>
</FanControlConfigV2>

**Comment by NavidDanesh** [comment]
Sorry
I can't attach the xml to my post and don't know what to do!
[https://github.com/NavidDanesh/nbfc/blob/master/Configs/Asus%20Vivobook%20TP301UA.xml](url)

**Comment by hirschmann** [comment]
I've added the config myself, see 2998a2de1993a1ecd7dc5df64fcd779aaf159fa6

**Pull request closed without merging**
