### PR TITLE
Added HP Envy x360 13-ag0xxx Fan Config. Requires Ryzen Support

### LINKED ISSUE #540: Fan Support for HP Envy X360 13-ag0000 Ryzen Notebooks (done, but waiting for requirements)
Hi @hirschmann , 

I completed the Fan Support for the HP Envy X360 13 Inch 13-ag0000 Model. 
The config works perfectly, but requires my patches to nbfc to support AMD Ryzen cpus. 

I will send a pull request with the working, when #538 is merged. This will make many Ryzen users happy :-)

Cheers,

Daniel

### PR DESCRIPTION
**Pull request by dan-and**
Added HP Envy x360 13-ag0xxx Fan Config. 

Requires Ryzen Support in NBFC to work.

Fixes #540

### CODE REVIEW

**Comment by dan-and** [comment]
Fan configs works fine with our "13-ag0700ng" and reported in reddit with a envy X360 13-ag0002

See: https://www.reddit.com/r/Amd/comments/96i4nv/hp_envy_x360_13_experiences_2500u_8gb_fix_to/e4as5h7/

**Comment by hirschmann** [comment]
Perfect! Thank you very much!

**Comment by luisfilipe46** [comment]
Hi @dan-and !

I'm trying to use your configurations in a new HP Envy x360 13-ag003np.
Unfortunately the configurations are not being used and I don't know how to fix it.

The actual behaviour is the following:
- Fan percentage usage is always the value in the "target fan speed". "target fan speed" is set manually.
- Fan percentage increases to 100% when the CPU reaches the critical temperature.

Do you find some behaviour which is similiar to this one?
I'm using nbfc version 1.6.3.

**Comment by dan-and** [comment]
Hi @luisfilipe46 
This is pretty weird. Could you give me some more insights of your exact envy model? 
What BIOS version are you using? 
What CPU? 
Which (I assume) windows 10 version?

**Comment by luisfilipe46** [comment]
The envy model is presented above - HP Envy x360 13-ag003np.
The CPU is a Ryzen 7 2700U.

I will send you soon the Windows 10 version and BIOS version.

**Comment by luisfilipe46** [comment]
**BIOS** version: F.35


Details about **Windows** version:
- Windows 10 Home
- Version 1803
- OS Build 17134.753
- 64-bit operating system, x64-based processor

**Comment by dan-and** [comment]
Hi @luisfilipe46 
I checked out the firmware of the model, which I used to create the nbfc profile. It runs on a BIOS version F.32 
I will check out from other owners of the X360 x360 13-ag0000 if they have similar issues and which BIOS versions they are using. It "could" be that HP locked up the possibility to change the Registers to control the fan. Dell does similar things in the past. 

I will get back on you again

**Comment by luisfilipe46** [comment]
I found the issue. Looks like by default the nbfc doesn't run in auto control mode. That was the issue. After running a nbdc.exe set -a everything started to work as excepted. In the interface I didn't found any place to enable the auto control mode. 

I can confirm that your configuration works on the HP Envy x360 13-ag003np model as expected.

**Pull request merged**
